services:
  db:
    image: postgres:16-alpine
    container_name: destinoperu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: destinoperu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d destinoperu"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: DestinoPeruAPI/Dockerfile
    container_name: destinoperu-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DisableHttpsRedirection: "true"
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=destinoperu;Username=postgres;Password=postgres
      JwtSettings__SecretKey: SuperSecretKeyForDestinoPeruDev_Minimo32Caracteres!
      JwtSettings__Issuer: DestinoPeru
      JwtSettings__Audience: DestinoPeruClients
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
